[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning
[secrets_scanning]
  enabled = true

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 